[package]
name = "saddle-ai-navmesh-example-dynamic-obstacles"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = { workspace = true }
saddle-pane = { workspace = true }
saddle-ai-navmesh = { workspace = true }
saddle-ai-navmesh-example-common = { path = "../common" }

[lints]
workspace = true
